//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.16 at 08:51:03 PM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ec.europa.eu:taxud:vies:services:checkVat:types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ayesa.wsdl;
